Run cmake-format checks during CI as well

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -15,10 +15,17 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
+    - uses: actions/setup-python@v5
+      with: { python-version: "3.12" }
+
+    - name: Install cmakelang
+      run: pip3 install cmakelang
+
     - name: Configure dummy project
       run: cmake -B build-fmt -DGPXPY_BUILD_CORE=OFF -D CLANG_FORMAT_PROGRAM=$(which clang-format-18)
 
-    - name: Check Formatting
+    - name: Check code formatting
+      id: clangformat
       run: |
         set +e
         cmake --build build-fmt --target check-clang-format
@@ -31,9 +38,30 @@ jobs:
           echo "No formatting errors found!"
         fi
 
+    - name: Check CMake formatting
+      # Let's run the CMake formatting checks even if our code is mis-formatted.
+      if: success() || steps.clangformat.conclusion == 'failure'
+      # Note that diff generation for cmake-format is somewhat broken in the upstream project.
+      # Diffs always end up with incorrect paths so manual fixes would be necessary, which we sidestep
+      # by re-formatting in-place and then using `git diff`.
+      run: |
+        set +e
+        cmake --build build-fmt --target check-cmake-format
+        status=$?
+        if [ $status -ne 0 ]; then
+          echo "Formatting errors found!"
+          cmake --build build-fmt --target fix-cmake-format
+          git diff > cmake-format.patch
+          exit $status
+        else
+          echo "No formatting errors found!"
+        fi
+
     - name: Upload Patch
       if: failure()
       uses: actions/upload-artifact@v4
       with:
-        name: clang-format-patch
-        path: clang-format.patch
+        name: Formatting fix .patch files
+        path: |
+          clang-format.patch
+          cmake-format.patch
